version: "3"

services:
  # --- Service de Stockage (S3 Compatible) ---
  minio:
    image: minio/minio:latest
    container_name: minio
    hostname: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - "9000:9000"  # Port API (utilisé par Dremio)
      - "9001:9001"  # Port Console Web (pour créer vos buckets)
    volumes:
      - ./minio-data:/data  # Persistance des données sur votre PC
    command: server /data --console-address ":9001"
    networks:
      - data-lake-network

  # --- Service de Requête (Data Lakehouse) ---
  dremio:
    image: dremio/dremio-oss:latest
    container_name: dremio
    hostname: dremio
    ports:
      - "9047:9047"   # Interface Web Dremio
      - "31010:31010" # Port pour connecter PowerBI/Tableau plus tard
    environment:
      - DREMIO_JAVA_SERVER_EXTRA_OPTS=-Dpaths.dist=file:///opt/dremio/data/dist
    networks:
      - data-lake-network

networks:
  data-lake-network: